name: "Pyright: Type Checking"

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python and dependencies
        uses: ./.github/actions/setup-python-uv
      - name: Run Pyright
        run: |
          source .venv/bin/activate
          pyright
