# pyright.yml

name: "Pyright: Type Checking"

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    name: "type-check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install 3.12
      
      - name: Create venv
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml --extra dev
      
      - name: Run Pyright
        run: |
          source .venv/bin/activate
          pyright
        
