name: "Publish"

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    name: "Build and publish release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python and dependencies
        uses: ./.github/actions/setup-python-uv
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
